require('user.plugins-setup')
require('user.core.options')
require('user.core.keymaps')
require('user.core.autocommand')
require('user.core.colorscheme')

require('user.plugins.nvim-tree')
require('user.plugins.lualine')
require('user.plugins.bufferline')
require('user.plugins.comment')
require('user.plugins.todo-comments')
require('user.plugins.telescope')
require('user.plugins.colorizer')
